---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: true
configure_zsh: true
# Plugin names have to be in the format github_user/plugin_name
zsh_plugins:
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-history-substring-search

# Theme names have to be in the format github_user/theme_name
zsh_themes:
  - romkatv/powerlevel10k

configure_tmux: true
tmux_dir: $HOME/.tmux

create_directories: true
directories:
  - $HOME/Documents/repositories

install_extra_packages: true
pip_packages:
  - name: pip
    state: latest

npm_packages:
  - name: neovim
    state: latest

install_fonts: true
installed_nerdfonts:
  - Meslo

homebrew_installed_packages:
  - fzf
