---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: true
configure_zsh: true
zsh_plugins:
  - zsh-syntax-highlighting
  - zsh-history-substring-search

configure_tmux: true
tmux_dir: $HOME/.tmux

create_directories: true
directories:
  - $HOME/Documents/repositories

install_extra_packages: true
pip_packages:
  - name: pip
    state: latest

npm_packages:
  - name: neovim
    state: latest

install_fonts: true
installed_nerdfonts:
  - Meslo

homebrew_installed_packages:
  - fzf
