---
- name: MacOS Playbook
  hosts: all

  vars_files:
    - example.config.yml

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["directories"]

    - name: Include extra-packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/extra-packages.yml
      when: install_extra_packages
      tags: ["extra-packages"]

    - name: Include fonts task configuration.
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include zsh task configuration.
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
      when: configure_zsh
      tags: ["zsh"]

    - name: Include user script task configuration.
      ansible.builtin.import_tasks:
        file: tasks/user_script.yml
      when: execute_script
      tags: ["script"]

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - name: Include tmux task configuration.
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      when: configure_tmux
      tags: ["tmux"]
