---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - import_tasks: tasks/directories.yml
      when: create_directories
      tags: ["directories"]

    - import_tasks: tasks/extra-packages.yml
      when: install_extra_packages
      tags: ["extra-packages"]

    - import_tasks: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - import_tasks: tasks/gpg.yml
      when: configure_gpg
      tags: ["gpg"]

    - import_tasks: tasks/oh-my-zsh.yml
      when: install_oh_my_zsh
      tags: ["ohmyz"]

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]

    - import_tasks: tasks/vundle.yml
      when: configure_vundle
      tags: ["vundle"]
