---
- name: MacOS Playbook
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["directories"]

    - name: Include extra-packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/extra-packages.yml
      when: install_extra_packages
      tags: ["extra-packages"]

    - name: Include fonts task configuration.
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include gpg task configuration.
      ansible.builtin.import_tasks:
        file: tasks/gpg.yml
      when: configure_gpg
      tags: ["gpg"]

    - name: Include oh-my-zsh task configuration.
      ansible.builtin.import_tasks:
        file: tasks/oh-my-zsh.yml
      when: install_oh_my_zsh
      tags: ["ohmyz"]

    - name: Include osx task configuration.
      ansible.builtin.import_tasks:
        file: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - name: Include tmux task configuration.
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      when: configure_terminal
      tags: ["terminal"]

    - name: Include terminal task configuration.
      ansible.builtin.import_tasks:
        file: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]

    - name: Include vim-plug task configuration.
      ansible.builtin.import_tasks:
        file: tasks/vim-plug.yml
      when: install_vim_plug
      tags: ["vim"]
