---
- name: Create gnupg hidden dir.
  ansible.builtin.file:
    path: "$HOME/.gnupg"
    state: directory
    mode: "0700"
  register: gnupg_dir

- name: Copy gpg-agent.conf.
  ansible.builtin.copy:
    src: "files/gpg/gpg-agent.conf"
    dest: "{{ gnupg_dir.path }}/gpg-agent.conf"
    mode: "0600"

- name: Copy gpg.conf.
  ansible.builtin.copy:
    src: "files/gpg/gpg.conf"
    dest: "{{ gnupg_dir.path }}/gpg.conf"
    mode: "0600"
