---
- name: Get current Terminal profile.
  ansible.builtin.command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  ansible.builtin.copy:
    src: files/terminal/OneHalfDark.terminal
    dest: /tmp/OneHalfDark.terminal
    mode: 0755
  changed_when: false
  when: "'OneHalfDark.terminal' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  coansible.builtin.commandmmand: open /tmp/OneHalfDark.terminal
  changed_when: false
  when: "'OneHalfDark.terminal' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string OneHalfDark
    - defaults write com.apple.terminal 'Startup Window Settings' -string OneHalfDark
  changed_when: false
  when: "'OneHalfDark' not in terminal_theme.stdout"
