---
- name: Get current Terminal profile.
  ansible.builtin.command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Add custom Terminal profile.
  ansible.builtin.copy:
    src: files/terminal/Macchiato.terminal
    dest: /tmp/Macchiato.terminal
    mode: "0755"
  changed_when: false
  when: "'Macchiato.terminal' not in terminal_theme.stdout"

- name: Add custom Terminal profile.
  ansible.builtin.command: open /tmp/Macchiato.terminal
  changed_when: false
  when: "'Macchiato.terminal' not in terminal_theme.stdout"

- name: Set custom Terminal profile as default.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Macchiato
    - defaults write com.apple.terminal 'Startup Window Settings' -string Macchiato
  changed_when: false
  when: "'Macchiato' not in terminal_theme.stdout"
