---
- name: Clone a github repository.
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: $HOME/.vim/bundle/Vundle.vim
    clone: true
    update: true

- name: Ensure plugins set in .vimrc are installed.
  shell:
    cmd: vim -c "execute \"PluginInstall\" | qa"

- name: Ensure plugins set in .vimrc are updated.
  shell:
    cmd: vim -c "execute \"PluginUpdate\" | qa"
